language: java
jdk:
   - oraclejdk9
addons:
   sonarcloud:
      organization: "maxwellray-github"
      token:
         secure: dcedd31b17491dc5db7e4e1bcffae44030c52c6e
script:
   mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
